### PR TITLE
readme: add CORS note and module init

### PR DESCRIPTION
**Pull request by carver**
License: MIT
Signed-off-by: Jason Carver <ut96caarrs@snkmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
@carver this LGTM. not sure about the testing failures -- @krl?

**Comment by krl** [comment]
this will probably fly if rebased on current master

**Comment by jbenet** [comment]
@krl this is just a readme change, so prob doesnt need a rebase?

**Comment by jbenet** [comment]
merged.

**Pull request merged**
