### PR TITLE
fix vinyl-fs and add --recursive

### PR DESCRIPTION
**Pull request by jbenet**
4455d70 (Juan Batiz-Benet, 79 seconds ago)
  implements ipfs add --recursive

  added ipfs-add.js test tool.

5d73bea (Juan Batiz-Benet, 3 minutes ago)
  fix use of vinyl-fs

### CODE REVIEW

**Comment by diasdavid** [comment]
Nice!

This PR also touches all the code that was causing this issue - https://github.com/ipfs/electron-app/issues/23 , hopefully, it fixes it too :)

**Comment by jbenet** [comment]
@mappum you were right -- i rebased :)

**Comment by diasdavid** [comment]
woooooot \o/ :D

**Pull request merged**
